name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Set git tag
        run: |-
          echo v$(npx -c 'echo "$npm_package_version"') > TAG_NAME
          git tag $(cat TAG_NAME)
          git push origin $(cat TAG_NAME)
